#!/bin/bash
# Install required packaged missing from Debian
# Configure for UK setup

if [ $UID -ne 0 ]; then
  echo "Error: Must be root"
  exit 1
fi

echo "Configuring Debian..."

# Relink /bin/sh to bash
rm /bin/sh
ln -s bash /bin/sh

# Install missing packages
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get upgrade -qq
# Install packages required by LFS
apt-get install -qq -y bison gawk texinfo
# Install packages required by lfsbuild
apt-get install -qq -y bc wget
# Install optional packages to aid development
apt-get install -qq -y openssh-server shellcheck git

# Update keymap to UK
setxkbmap gb

echo "IP : $(hostname -I | cut -d ' ' -f 1)"
