#!/bin/bash
# Install required packaged missing from Debian
# Configure for UK setup

if [ $UID -ne 0 ]; then
  echo "Error: Must be root"
  exit 1
fi

echo "Configuring Debian..."

# Relink /bin/sh to bash
rm /bin/sh
ln -s bash /bin/sh

# Install missing packages
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get upgrade
# Install packages required by LFS
apt-get install -y bison gawk texinfo
# Install packages required by lfsbuild
apt-get install -y bc wget
# Install optional packages to aid development
apt-get install -y openssh-server shellcheck git

# Update keymap to UK
setxkbmap gb
# Set time to GB time.
rm /etc/localtime
ln -s /usr/share/zoneinfo/GB /etc/localtime

echo "IP : $(hostname -I | cut -d ' ' -f 1)"
